# Generated by Django 3.1.5 on 2021-02-03 05:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('opcion_1', models.CharField(default=None, max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'El menu debe contener al menos 5 caracteres'), django.core.validators.MaxLengthValidator(100, 'Ingresar dni en el siguiente formato 77111666-5')])),
                ('opcion_2', models.CharField(default=None, max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'El menu debe contener al menos 5 caracteres'), django.core.validators.MaxLengthValidator(100, 'El menu debe contener maximo 5 caracteres')])),
                ('opcion_3', models.CharField(default=None, max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'El menu debe contener al menos 5 caracteres'), django.core.validators.MaxLengthValidator(100, 'El menu debe contener al menos 5 caracteres')])),
                ('opcion_4', models.CharField(default=None, max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'El menu debe contener al menos 5 caracteres'), django.core.validators.MaxLengthValidator(100, 'El menu debe contener al menos 5 caracteres')])),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'El menu debe contener al menos 5 caracteres'), django.core.validators.MaxLengthValidator(100, 'Ingresar dni en el siguiente formato 77111666-5')])),
                ('opcion', models.CharField(choices=[('opcion_1', 'opcion_1'), ('opcion_2', 'opcion_2'), ('opcion_3', 'opcion_3'), ('opcion_4', 'opcion_4')], default='Selecciona tu opción', max_length=15)),
                ('comentario', models.CharField(default=None, max_length=60, validators=[django.core.validators.MinLengthValidator(2, 'Tu comentario no se entiende'), django.core.validators.MaxLengthValidator(60, 'Tu comentario puede tener hasta 60 caracteres')])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rutUsuario', models.CharField(default=None, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9, 'Ingresar dni en el siguiente formato 77111666-5'), django.core.validators.MaxLengthValidator(10, 'Ingresar dni en el siguiente formato 77111666-5')])),
                ('usuario', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
