# Generated by Django 3.1.5 on 2021-01-28 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha',
            field=models.DateField(max_length=60, validators=[django.core.validators.MinLengthValidator(5, 'Ingresar Fecha en formato AAAA-MM-DD'), django.core.validators.MaxLengthValidator(60, 'Ingresar dni en el siguiente formato 77111666-5')]),
        ),
    ]
