# Generated by Django 3.1.5 on 2021-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nora', '0002_auto_20210128_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha',
            field=models.DateField(),
        ),
    ]
