# Generated by Django 3.1.5 on 2021-01-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nora', '0003_auto_20210128_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
