# Generated by Django 3.1.5 on 2021-02-01 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_nora', '0005_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rutUsuario',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(9, 'Ingresar dni en el siguiente formato 77111666-5'), django.core.validators.MaxLengthValidator(10, 'Ingresar dni en el siguiente formato 77111666-5')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('opcion', models.CharField(choices=[('opcion_1', 'opcion_1'), ('opcion_2', 'opcion_2'), ('opcion_3', 'opcion_3'), ('opcion_4', 'opcion_4')], default='Selecciona tu opción', max_length=15)),
                ('comentario', models.CharField(default=None, max_length=60, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2, 'Tu comentario no se entiende'), django.core.validators.MaxLengthValidator(60, 'Tu comentario puede tener hasta 60 caracteres')])),
                ('rutUsuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_nora.usuario')),
            ],
        ),
    ]
